"""
ai_engine.py

This module connects the Python student-support system
to the Groq LLM.

Flow:

Backend
   ↓
ai_prompt_context
   ↓
This module
   ↓
Groq LLM
   ↓
Structured JSON response
"""


import os
import json


from groq import Groq

from prompts import SYSTEM_PROMPT, create_ai_prompt
import os
from pathlib import Path

from dotenv import load_dotenv


# Get the folder where ai_engine.py is located
BASE_DIR = Path(__file__).resolve().parent

# Explicitly tell Python where the .env file is
ENV_FILE = BASE_DIR / ".env"

# Load environment variables from that file
load_dotenv(ENV_FILE)

# =========================================================
# LOAD ENVIRONMENT VARIABLES
# =========================================================




# Get the API key from .env
API_KEY = os.getenv("GROQ_API_KEY")


# Stop the program early if the API key is missing.
if not API_KEY:

    raise ValueError(
        "GROQ_API_KEY not found.\n"
        "Please create a .env file and add:\n"
        "GROQ_API_KEY=your_api_key"
    )


# =========================================================
# INITIALIZE GROQ CLIENT
# =========================================================

client = Groq(api_key=API_KEY)


# =========================================================
# MODEL
# =========================================================

MODEL_NAME = "openai/gpt-oss-120b"


# =========================================================
# MAIN AI FUNCTION
# =========================================================

def get_ai_response(ai_context, student_message=None):
    """
    Generate an AI response using the backend context.

    Parameters
    ----------
    ai_context : str
        Context generated by Rishik's backend.

    student_message : str, optional
        Current message from the student.

    Returns
    -------
    dict
        Structured AI response.
    """

    # -----------------------------------------------------
    # Build the prompt.
    # -----------------------------------------------------

    user_prompt = create_ai_prompt(
        ai_context,
        student_message
    )


    try:

        # -------------------------------------------------
        # Send request to Groq.
        # -------------------------------------------------

        response = client.chat.completions.create(

            model=MODEL_NAME,

            messages=[
                {
                    "role": "system",
                    "content": SYSTEM_PROMPT
                },
                {
                    "role": "user",
                    "content": user_prompt
                }
            ],

            # Lower temperature gives more consistent
            # structured responses.
            temperature=0.3
        )


        # -------------------------------------------------
        # Get the text returned by the model.
        # -------------------------------------------------

        raw_response = (
            response
            .choices[0]
            .message
            .content
            .strip()
        )


        # -------------------------------------------------
        # Convert JSON text into a Python dictionary.
        # -------------------------------------------------

        try:

            result = json.loads(raw_response)

        except json.JSONDecodeError:

            # Sometimes models wrap JSON in Markdown.
            cleaned_response = (
                raw_response
                .replace("```json", "")
                .replace("```", "")
                .strip()
            )

            result = json.loads(cleaned_response)


        return result


    except Exception as error:

        # -------------------------------------------------
        # Return a controlled error instead of crashing
        # the entire application.
        # -------------------------------------------------

        return {
            "error": str(error)
        }
