"""
chatbot.py

Context-aware chatbot for the AI Student Check-in &
Support System.

The chatbot remembers:
    1. The student's backend-generated support context
    2. Previous messages in the conversation
    3. The student's latest message

This allows the AI to have a continuous conversation
instead of treating every message as a completely
new question.
"""


import os
import json

from groq import Groq
from dotenv import load_dotenv

from prompts import SYSTEM_PROMPT


# =========================================================
# LOAD ENVIRONMENT VARIABLES
# =========================================================

load_dotenv()


# Get the Groq API key.
API_KEY = os.getenv("GROQ_API_KEY")
if not API_KEY:
    for candidate_path in ["GROQ_API.key", "../GROQ_API.key"]:
        if os.path.exists(candidate_path):
            with open(candidate_path, "r", encoding="utf-8") as f:
                API_KEY = f.read().strip()
                if API_KEY:
                    break

# Make sure the API key exists.
if not API_KEY:
    raise ValueError(
        "GROQ_API_KEY not found.\n"
        "Please check your .env or GROQ_API.key file."
    )


# =========================================================
# INITIALIZE GROQ
# =========================================================

client = Groq(api_key=API_KEY)


# =========================================================
# MODEL
# =========================================================

MODEL_NAME = "openai/gpt-oss-120b"


# =========================================================
# CHATBOT CLASS
# =========================================================

class StudentSupportChatbot:
    """
    Context-aware chatbot for a single student session.

    Each chatbot object stores:
        - Student support context
        - Conversation history
    """

    def __init__(self, ai_context):
        """
        Initialize the chatbot.

        Parameters
        ----------
        ai_context : str
            Context generated by Rishik's backend.
        """

        # Store the student's backend context.
        self.ai_context = ai_context

        # Store conversation messages.
        self.conversation_history = []


    # =====================================================
    # ADD MESSAGE TO HISTORY
    # =====================================================

    def add_message(self, role, content):
        """
        Add a message to the conversation history.

        Parameters
        ----------
        role : str
            Either "user" or "assistant".

        content : str
            Message content.
        """

        self.conversation_history.append({
            "role": role,
            "content": content
        })


    # =====================================================
    # GENERATE CHATBOT RESPONSE
    # =====================================================

    def get_response(self, student_message):
        """
        Generate a response to the student's message.

        The AI receives:
            - System instructions
            - Student's backend context
            - Previous conversation
            - Current message

        Parameters
        ----------
        student_message : str
            Current message from the student.

        Returns
        -------
        dict
            AI-generated response.
        """

        # -------------------------------------------------
        # Add the student's message to history.
        # -------------------------------------------------

        self.add_message(
            "user",
            student_message
        )


        # -------------------------------------------------
        # Build the system context.
        # -------------------------------------------------

        chatbot_system_prompt = f"""
{SYSTEM_PROMPT}

=========================================================
STUDENT BACKEND CONTEXT
=========================================================

{self.ai_context}

=========================================================
IMPORTANT
=========================================================

The backend context above contains information generated
by the Python student-support system.

Use it to personalize your responses.

Do NOT expose the backend context directly to the student.

You may use the context to understand:

- Support level
- Risk flags
- Historical trends
- Study strategy
- Remaining workload
- Whether an extension may be needed

=========================================================
CHATBOT BEHAVIOR
=========================================================

You are having an ongoing conversation with the student.

Remember previous messages in the conversation.

Do not repeat the same advice unnecessarily.

If the student asks about their workload:
use the workload and study strategy information.

If the student asks what to do next:
give practical prioritized actions.

If the backend says an extension may be needed:
offer to help draft an extension email when relevant.

If the student asks for a study schedule:
help break the work into manageable blocks.

If the student asks for emotional support:
respond supportively without diagnosing.

Return ONLY valid JSON.
"""


        # -------------------------------------------------
        # Build message list for Groq.
        # -------------------------------------------------

        messages = [

            {
                "role": "system",
                "content": chatbot_system_prompt
            }

        ]


        # Add previous conversation.
        messages.extend(
            self.conversation_history
        )


        try:

            # -------------------------------------------------
            # Send request to Groq.
            # -------------------------------------------------

            response = client.chat.completions.create(

                model=MODEL_NAME,

                messages=messages,

                temperature=0.3
            )


            # -------------------------------------------------
            # Extract response.
            # -------------------------------------------------

            raw_response = (
                response
                .choices[0]
                .message
                .content
                .strip()
            )


            # -------------------------------------------------
            # Convert JSON response to Python dictionary.
            # -------------------------------------------------

            try:

                result = json.loads(raw_response)

            except json.JSONDecodeError:

                # Remove Markdown code fences if the model
                # accidentally surrounds the JSON with them.

                cleaned_response = (
                    raw_response
                    .replace("```json", "")
                    .replace("```", "")
                    .strip()
                )

                result = json.loads(cleaned_response)


            # -------------------------------------------------
            # Store assistant response in history.
            # -------------------------------------------------

            # Store only the conversational message,
            # rather than the entire JSON object.
            assistant_message = result.get(
                "message",
                ""
            )


            self.add_message(
                "assistant",
                assistant_message
            )


            return result


        except Exception as error:

            # -------------------------------------------------
            # Return controlled error.
            # -------------------------------------------------

            return {
                "error": str(error)
            }


    # =====================================================
    # CLEAR CHAT
    # =====================================================

    def clear_history(self):
        """
        Clear the current conversation history.

        The student's backend context remains available.
        """

        self.conversation_history = []